version: '2'
services:
  # redis:
  #   image: "redis:alpine"
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  database:
    image: "postgres:9.6"
    ports:
      - "5432:5432"
    container_name: database
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
#  metabase:
#    image: "metabase/metabase"
#    ports:
#      - "3000:3000"
